### ISSUE TITLE
Threading not working well for ctb-tile?

### ISSUE THREAD

**Issue by GeorgeDewar** [geo-data/cesium-terrain-builder#17]
We are getting approx 150 tiles per second processed on a layer 16 run with ctb-tile if we specify 1 thread, rising only to 400 tiles per second at 8 threads (on an 8-core machine).

We have tried this on a 36-core machine and the performance with 36 threads (the default setting being 1 per core) is no improvement whatsoever over 8 threads.

These are both EC2 servers. We have tried using a RAM drive for storage to eliminate the possibly of a disk bottleneck. We tend to see a load average of around the number of threads, and CPU utilization per core of around 70%.

If we ran another job at the same time, we can get utilization to 100%, but overall throughput is actually less.

The most peculiar thing is that on an Intel Core i5 destop machine, we get about 2000 tiles per second - dramatically better performance than the 36-core AWS box. We are not sure why.

Any tips? Here's the command we're running:

```ctb-tile --output-dir tiles3 -s 16 -e 16 -m 8000000000 -c n dem_wgs84.vrt```

Where n above is of course the various thread counts we have tried. Using more threads than cores also does not help, though I wouldn't expect it to.

Please let me know if any additional information would be helpful.

**Comment by GeorgeDewar** [comment]
Since writing this I have read some things that make me suspect that the bottleneck is the file system - not disk I/O, but creating files. Interesting...

**Comment by homme** [comment]
Hello -  CTB's use of threads is simple and in an ideal world I'd expect it to scale linearly with the number of cores.  As such any failure to meet this expectation in practice will almost certainly be due to a bottle neck in a subsystem.  The problem will be narrowing it down to which one! 

GDAL itself may be the culprit as it is a pretty complex beast with a [plethora of config options](http://trac.osgeo.org/gdal/wiki/ConfigOptions) and drivers which can interact in subtle ways (especially cache related options such as `GDAL_MAXCACHE`).  There is also room for improvement: for example I notice you are using a VRT and if it is referencing many source datasets then implementing [this issue](http://trac.osgeo.org/gdal/ticket/5762) may help.

However, your hunch that it could be the filesystem may well turn out to be true; I have had problems with this in the past. In this case it may be worth looking at a filesystem optimised for many small files, such as ReiserFS running on solid state disks.

Assuming funds and time I would like to implement different cache backends to CTB in addition to the filesystem (e.g. memcache, redis, postgis, leveldb, sqlite) which could be used to help scale and overcome filesystem bottlenecks.  

I would be interested in any findings you have, as it would be useful to set up a tuning section in the README to help with these issues.

**Comment by GeorgeDewar** [comment]
Thanks @homme! The VRT in this case was only referencing a couple of hundred images, which I imagine wouldn't have been too taxing for it.

We're done with our big processing task now, so may not get to put a lot more time into testing different file systems but will keep ReiserFS in mind. We will let you know if we have the opportunity to experiment further and find out anything useful :)

**Comment by mrgloom** [comment]
In `htop` on 32 core machine I can see that utilization of cores is not full.

Also any recommendations about `-m` parameter?
